version: '3'

services:
  web:
    restart: always
    build: .
    ports:
      - "8000:8000"
    command: daphne -b 0.0.0.0 -p 8000 nateste.asgi:application
    links:
      - redis



  redis:
    restart: always
    image: redis:5
    ports:
    - "6379:6379"