# Generated by Django 3.0.7 on 2020-07-04 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_auto_20200625_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='main_api.Profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_order', to='main_api.Profile'),
        ),
    ]
