# Generated by Django 3.0.7 on 2020-07-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='id_in_user_list',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
