# Generated by Django 3.0.7 on 2020-07-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_id_in_user_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='was_read',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='was_read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
